# Generated by Django 4.1.3 on 2022-12-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tematica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tema', models.CharField(max_length=40)),
                ('autor', models.CharField(max_length=40)),
                ('codigo', models.CharField(max_length=40)),
            ],
        ),
    ]
